title: A Memer's Guide to Rickrolling
author: Serenus
email: cseanwyatt@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Rickrolling is a memetic phenomenon where one "bamboozles" or tricks someone into falling for the various media that end up with them listening to Rick Astley's "Never Gonna Give You Up".
  Don't believe me? Then [don't](https://youtube.com/watch?v=dQw4w9WgXcQ).

# social links
twitter_username: mlgcream # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
